'use strict';

// JQuery requires some extra tweaking as it is expected to be
// on the window.$ element.
window.$    = window.jQuery = require('jquery')
var angular = require('angular');

// Imports for angular-schema-form. This should not be needed.
require('tv4');
window.ObjectPath = require('objectpath');
require('angular-sanitize');
require('bootstrap-sass');
require('angular-schema-form');

// angular modules
require('angular-ui-router');
// templates are generated by the build process. This transforms
// the views to use the template cache.
require('./templates');
require('./exampleFeature/_index');
require('./formFeature/_index');


// create and bootstrap application
angular.element(document).ready(function() {

  var requires = [
    'ui.router',
    'templates',
    'schemaForm',

    // our application feature modules. change.
    'tc.exampleFeature',
    'tc.formFeature'
  ];

  // mount on window for testing
  window.app = angular.module('app', requires);

  angular.module('app').constant('AppSettings', require('./constants'));

  angular.module('app').config(require('./on_config'));

  angular.module('app').run(require('./on_run'));

  angular.bootstrap(document, ['app']);

});
